package Phili.GUI;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Phili.MainEngine.Product;

/**
 * @author phili
 *
 */
public class AddNewItemUI extends javax.swing.JFrame{
	
    private javax.swing.JButton aniButtonAdd;
    private javax.swing.JButton aniButtonDialogOK;
    private javax.swing.JButton aniButtonReset;
    private javax.swing.JComboBox<String> aniComboboxCategory;
    private javax.swing.JDialog aniFrameDialog;
    private javax.swing.JLabel aniLabelCategory;
    private javax.swing.JLabel aniLabelDescription;
    private javax.swing.JLabel aniLabelDialog;
    private javax.swing.JLabel aniLabelIncomplete;
    private javax.swing.JLabel aniLabelName;
    private javax.swing.JLabel aniLabelPrice;
    private javax.swing.JLabel aniLabelQuantity;
    private javax.swing.JPanel aniPanel;
    private javax.swing.JScrollPane aniScrollPaneDescription;
    private javax.swing.JSpinner aniSpinnerQuantity;
    private javax.swing.JTextArea aniTextAreaDescription;
    private javax.swing.JTextField aniTextFieldName;
    private javax.swing.JTextField aniTextFieldPrice;

    public AddNewItemUI() {
       
        initComponents();
        
        LoginUI.uiLogic.InitializeSpinner(aniSpinnerQuantity);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        aniFrameDialog = new javax.swing.JDialog();
        aniLabelDialog = new javax.swing.JLabel();
        aniButtonDialogOK = new javax.swing.JButton();
        aniPanel = new javax.swing.JPanel();
        aniLabelPrice = new javax.swing.JLabel();
        aniLabelCategory = new javax.swing.JLabel();
        aniComboboxCategory = new javax.swing.JComboBox<>();
        aniTextFieldName = new javax.swing.JTextField();
        aniScrollPaneDescription = new javax.swing.JScrollPane();
        aniTextAreaDescription = new javax.swing.JTextArea();
        aniTextFieldPrice = new javax.swing.JTextField();
        aniLabelName = new javax.swing.JLabel();
        aniButtonAdd = new javax.swing.JButton();
        aniLabelDescription = new javax.swing.JLabel();
        aniButtonReset = new javax.swing.JButton();
        aniLabelQuantity = new javax.swing.JLabel();
        aniSpinnerQuantity = new javax.swing.JSpinner();
        aniLabelIncomplete = new javax.swing.JLabel();

        aniFrameDialog.setTitle("Dialog");
        aniFrameDialog.setLocationByPlatform(true);
        aniFrameDialog.setMinimumSize(new java.awt.Dimension(320, 120));
        aniFrameDialog.setResizable(false);

        aniLabelDialog.setText("The new product has been added to the database");

        aniButtonDialogOK.setText("OK");
        aniButtonDialogOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniButtonDialogOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aniFrameDialogLayout = new javax.swing.GroupLayout(aniFrameDialog.getContentPane());
        aniFrameDialog.getContentPane().setLayout(aniFrameDialogLayout);
        aniFrameDialogLayout.setHorizontalGroup(
            aniFrameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aniFrameDialogLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(aniFrameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(aniButtonDialogOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aniLabelDialog))
                .addGap(28, 28, 28))
        );
        aniFrameDialogLayout.setVerticalGroup(
            aniFrameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aniFrameDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(aniLabelDialog)
                .addGap(18, 18, 18)
                .addComponent(aniButtonDialogOK)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add new item");
        setBackground(new java.awt.Color(255, 0, 51));
        setResizable(false);

        aniPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter new item's characteristics"));

        aniLabelPrice.setText("Price:");

        aniLabelCategory.setText("Category:");

        aniComboboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Electronics", "Clothing" }));

        aniTextAreaDescription.setColumns(20);
        aniTextAreaDescription.setRows(5);
        aniScrollPaneDescription.setViewportView(aniTextAreaDescription);

        aniLabelName.setText("Name:");

        aniButtonAdd.setBackground(java.awt.SystemColor.controlHighlight);
        aniButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phili/GUI/Images/plus2.png"))); 
        aniButtonAdd.setText("Add");
        aniButtonAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aniButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniButtonAddActionPerformed(evt);
            }
        });

        aniLabelDescription.setText("Description:");

        aniButtonReset.setBackground(java.awt.SystemColor.controlHighlight);
        aniButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phili/GUI/Images/reset copy.png")));
        aniButtonReset.setText("Reset");
        aniButtonReset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aniButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniButtonResetActionPerformed(evt);
            }
        });

        aniLabelQuantity.setText("Quantity:");

        aniSpinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        aniLabelIncomplete.setText(" ");

        javax.swing.GroupLayout aniPanelLayout = new javax.swing.GroupLayout(aniPanel);
        aniPanel.setLayout(aniPanelLayout);
        aniPanelLayout.setHorizontalGroup(
            aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aniPanelLayout.createSequentialGroup()
                        .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aniLabelCategory)
                            .addComponent(aniLabelPrice)
                            .addComponent(aniLabelDescription)
                            .addComponent(aniLabelName)
                            .addComponent(aniLabelQuantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aniScrollPaneDescription)
                            .addComponent(aniTextFieldName)
                            .addComponent(aniTextFieldPrice)
                            .addComponent(aniComboboxCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(aniPanelLayout.createSequentialGroup()
                        .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aniSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aniLabelIncomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aniButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aniButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        aniPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aniButtonAdd, aniButtonReset});

        aniPanelLayout.setVerticalGroup(
            aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aniLabelName)
                    .addComponent(aniTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aniLabelDescription)
                    .addComponent(aniScrollPaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aniLabelPrice)
                    .addComponent(aniTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aniLabelCategory)
                    .addComponent(aniComboboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aniPanelLayout.createSequentialGroup()
                        .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aniButtonReset)
                            .addComponent(aniButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(aniPanelLayout.createSequentialGroup()
                        .addGroup(aniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aniLabelQuantity)
                            .addComponent(aniSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aniLabelIncomplete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        aniPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aniButtonAdd, aniButtonReset});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }
    private void aniButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
        
        
        boolean validator = ValidateAdd();
        
        if(validator)
        {
            Product product = new Product();
            
            product = LoginUI.uiLogic.GetFrameContent(aniTextFieldName, aniTextAreaDescription, aniTextFieldPrice, aniComboboxCategory, aniSpinnerQuantity);
            
            LoginUI.controller.AddProduct(product.getName(), product.getCategory(), product.getPrice(), product.getQuantity(), product.getDescription());

            MainUI.productsList = LoginUI.controller.getListOfProducts();
            
            aniFrameDialog.setVisible(true);
            
            this.dispose();
        }
        else
        {
            aniLabelIncomplete.setText("Incomplete fields!");
        }
    }

    private void aniButtonResetActionPerformed(java.awt.event.ActionEvent evt) {
       
        aniTextFieldName.setText(null);
        aniTextAreaDescription.setText(null);
        aniTextFieldPrice.setText(null);
        aniComboboxCategory.setSelectedIndex(0);
    }

    private void aniButtonDialogOKActionPerformed(java.awt.event.ActionEvent evt) {
        
        aniFrameDialog.dispose();   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

   
        try {
            
        UIManager.setLookAndFeel(
            UIManager.getCrossPlatformLookAndFeelClassName());
    } 
    catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       
    }
        
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewItemUI().setVisible(true);
        });
    }


    
    public boolean ValidateAdd()
    {
        return !"".equals(aniTextFieldName.getText()) && !"".equals(aniTextFieldPrice.getText()) && (Integer.parseInt(aniSpinnerQuantity.getValue().toString())!=0);
    }
}
