package Phili.GUI;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 * @author phili
 *
 */
public final class OrdersUI extends javax.swing.JFrame {
	
	
	private javax.swing.JButton OrdersButtonLogout;
    private javax.swing.JPanel OrdersPanel;
    private javax.swing.JScrollPane OrdersScollPane;
    private javax.swing.JTable OrdersTable;
    
    
    public OrdersUI() {
        initComponents();
       
        LoginUI.uiLogic.Query(OrdersTable, MainUI.ordersList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        OrdersPanel = new javax.swing.JPanel();
        OrdersScollPane = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();
        OrdersButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orders");
        setMinimumSize(new java.awt.Dimension(350, 300));

        OrdersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Orders"));

        OrdersTable.setAutoCreateRowSorter(true);
        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrdersScollPane.setViewportView(OrdersTable);

        OrdersButtonLogout.setBackground(java.awt.SystemColor.controlHighlight);
        OrdersButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/UI/Images/logout2.png"))); 
        OrdersButtonLogout.setText("Log Out");
        OrdersButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrdersPanelLayout = new javax.swing.GroupLayout(OrdersPanel);
        OrdersPanel.setLayout(OrdersPanelLayout);
        OrdersPanelLayout.setHorizontalGroup(
            OrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrdersScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdersPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OrdersButtonLogout)))
                .addContainerGap())
        );
        OrdersPanelLayout.setVerticalGroup(
            OrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrdersScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrdersButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    private void OrdersButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {
        
        LoginUI loginForm = new LoginUI();
        
        loginForm.setVisible(true);
        
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
         try {
            
        UIManager.setLookAndFeel(
            UIManager.getCrossPlatformLookAndFeelClassName());
    } 
    catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       
    }

        java.awt.EventQueue.invokeLater(() -> {
            new OrdersUI().setVisible(true);
         });
    }

    

}
